Skip to content
DEV Community
Search...

Log in
Create account

3

3

0

Cover image for Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github 🐍
Henrique Lopes
Henrique Lopes
Posted on 4 de jan.

Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github 🐍
#
github
Primeiramente devo deixar claro que esse artigo foi desenvolvido com base em vários outros artigos e reconstruído para deixar o mais claro possível a forma para inserir o Snake Game em seu perfil.

Funcionamento. "Contributions in the last year":
Basicamente o Snake game funciona realizando uma coleta da sua tabela de contribuições no Github. ele faz a renderização dessas informações e gera dois arquivos, um em formato gif e outro em svg. São esses arquivos que iremos utilizar para inserir a animação no perfil do Github.

Repositorio do projeto a ser utilizado: Platane/snk

Exemple

Requisito. "Repositório base":
Para que você possa prosseguir é necessário que você tenha o repositório do perfil (repositório com o mesmo nome de usuário), porém para gerar os arquivos também funciona em outro repositório.

Actions. "Configuração inicial":
Inicialmente é necessário que você acesse o seu repositório escolhido e vá em Settings.

Configuração inicial

No menu vertical ao lado esquerdo selecione o menu Actions e em seguida ative a permissão “Allow all actions”. Também é possível selecionar diretamente o repositório.

Ative a permissão

Actions. "Criando Gerador":
Agora que temos o repositório configurado iremos adicionar o "script" para gerar dos arquivos. No repositório, vá em Actions.

Criando o gerador

Em seguida vamos utilizar “Simple workflow” apenas com o mínimo necessário para rodar o codigo.

Configurando

Agora é apenas alterar o nome do arquivo e colar o código da configuração com o seu usuário.

Alterar jnome do arquivo

alterando o username
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: viktorsoares #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Retornando na opção Actions do repositório, clique em “Run workflow”:

Repositorio

Pasta dos arquivos:
Em seu repositorio cliente em main e selecione a branch output:
output

E aqui estão os arquivos gerados que você pode utilizar como bem entender:

Arquivos

Codigo Github para utilização:

![snake gif](https://github.com/SEU_USUARIO/SEU_REPOSITORIO/blob/output/github-contribution-grid-snake.svg)

Discussion (0)
Subscribe
pic
Add to the discussion
Code of Conduct • Report abuse
Read next
mishmanners profile image
GitHub's non-code features: exploring more of GitHub and encouraging your non-dev friends
Michelle Mannering - Jul 15

sadeedpv profile image
Someone copied my code on Github and claimed it to be his own project.
Sadeedpv - Jul 15

jmfayard profile image
Is Git Great? #healthydebate
Jean-Michel Fayard 🇫🇷🇩🇪🇬🇧🇪🇸🇨🇴 - Jul 20

preethi_dev profile image
25 Extremely Modern Layouts Using CSS Grid✨
Preethi⚡ - Jul 20


Henrique Lopes
Follow
"Não há razão alguma em usar a palavra “impossível” para descrever algo que claramente pode acontecer."
JOINED
5 de set. de 2021
Trending on DEV Community 
Gracie Gregory (she/her) profile image
What was your win this week?
#discuss #weeklyretro
Christian Prado Ciokler profile image
150+ Typescript one-liners [code snippets].
#javascript #typescript #productivity
Zeeshan Safdar profile image
Understanding Git and Github
#github #git #beginners #programming
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nomeUsuario #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
DEV Community — A constructive and inclusive social network for software developers. With you every step of your journey.

Built on Forem — the open source software that powers DEV and other inclusive communities.

Made with love and Ruby on Rails. DEV Community © 2016 - 2022.
